### PR TITLE
Tests pass against RSpec 2.0.1

### PR DESCRIPTION
**Pull request by joefiorini**
The Rails 2.3.8 app I'm running it against is green too.

### CODE REVIEW

**Comment by joefiorini** [comment]
You still have rspec 2.0.0.beta8 as a runtime dependency. I had removed that line in my pull request. Can you please remove it so I can use the actual Gem instead of my Github fork? Thanks!

**Comment by daya** [comment]
hi joefiorini

how do you remove 2.0.0.beta8 runtime dependency in pull request ??

**Comment by daya** [comment]
never mind I think what you were referring to was gem install rspec-rails23 --ignore-dependencies

**Comment by rsanheim** [comment]
Closing as very old / stale.

**Pull request closed without merging**
